Vagrant.configure("2") do |config|
  config.vm.box = 'precise64'
  config.vm.box_url = 'http://files.vagrantup.com/precise64.box'
  # config.vm.box = "boot2docker"
  # config.vm.box_url = "https://github.com/mitchellh/boot2docker-vagrant-box/releases/download/v0.3.0/boot2docker.box"

  config.vm.network :forwarded_port, guest: 4243, host: 4243  # docker
  config.vm.network :forwarded_port, guest: 80,   host: 8082  # nginx
  config.vm.network :forwarded_port, guest: 8080, host: 8081  # datadex
  config.vm.network :forwarded_port, guest: 9200, host: 9200  # elasticsearch
  config.vm.network :forwarded_port, guest: 9300, host: 9300  # elasticsearch

  # config.vm.synced_folder "../", "/usr/local/go/src/github.com/jbenet/datadex"
  config.vm.synced_folder "data", "/data"

  config.vm.provision "docker", images: ["ubuntu"]

  config.vm.provision :shell, :inline => <<-eos
  echo 'DOCKER_OPTS="-H tcp://0.0.0.0:4243"' >> /etc/default/docker
  echo 'export DOCKER_HOST="tcp://0.0.0.0:4243"' >> /home/vagrant/.bashrc
  service docker restart
  mkdir -p /data/datadex/es
  eos

end
